name: Build & Push Docker Images

on:
  push:
    paths:
      - '.github/workflows/docker.yml'
      - '.devcontainer/Dockerfile.codespaces'
      - '.devcontainer/Dockerfile.ci'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push-images:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push Dev Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile.codespaces
          push: true
          tags: |
            ghcr.io/ulfbou/zentient-dev:latest
            ghcr.io/ulfbou/zentient-dev:${{ github.sha }}

      - name: Build & Push CI Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .devcontainer/Dockerfile.ci
          push: true
          tags: |
            ghcr.io/ulfbou/zentient-ci:latest
            ghcr.io/ulfbou/zentient-ci:${{ github.sha }}
